# Your personal GitHub token
github_token: <your-personal-github-token>
# Read more: https://github.com/blog/1509-personal-api-tokens
# You can generate it here: https://github.com/settings/tokens

# Guest OS timezone. Because i am in Indonesia!
timezone: Asia/Jakarta

# Are we need check box updates for every 'vagrant up'?
box_check_update: true

# Virtual machine name
machine_name: haqqi

# Virtual machine IP
ip: 192.168.77.77

# Virtual machine CPU cores number
cpus: 2

# Virtual machine RAM
memory: 1024